name: CrazyCrates-VirtualToPhysical
version: 1.3
main: me.Hayden.Crate.Addon.Main
description: Addon for crazycrates which allows the conversion of virtual keys to physical keys
depend: [CrazyCrates]
commands:
  virtualtophysical:
